# Generated by Django 4.0 on 2024-02-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]