# Generated by Django 4.1.4 on 2026-02-26 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('urgent', 'Urgent'), ('message', 'Message'), ('info', 'Informational')], max_length=20)),
                ('message', models.TextField(max_length=250)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
