# Generated by Django 4.0 on 2023-06-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KnownIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='install_instructions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='known_issues',
        ),
        migrations.AddField(
            model_name='project',
            name='install_instructions',
            field=models.ManyToManyField(to='projects.InstallInstruction'),
        ),
        migrations.AddField(
            model_name='project',
            name='known_issues',
            field=models.ManyToManyField(to='projects.KnownIssue'),
        ),
    ]
