# Generated by Django 4.0 on 2023-06-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(default='https://github.com/', max_length=75),
        ),
    ]
