# Generated by Django 4.0 on 2023-06-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_caption',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
