# Generated by Django 4.0 on 2023-06-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_image_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.ManyToManyField(to='projects.Feature'),
        ),
    ]
