# Generated by Django 4.0 on 2023-06-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
