# Generated by Django 4.0 on 2023-06-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_language_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('go', 'Go'), ('python', 'Python'), ('javascript', 'JavaScript'), ('other', 'Other')], default='go', max_length=30),
        ),
    ]
