# Generated by Django 4.0 on 2023-06-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('go', 'Go'), ('Python', 'Python'), ('Javascript', 'JavaScript'), ('Other', 'Other')], default='go', max_length=30),
        ),
    ]
