# Generated by Django 4.0 on 2023-07-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blur_dropdown', models.BooleanField(default=False)),
                ('black_footer', models.BooleanField(default=False)),
                ('typing_speed', models.BooleanField(default=False)),
                ('border_glow', models.BooleanField(default=False)),
                ('home_title', models.BooleanField(default=False)),
                ('title_seperator', models.CharField(default='-', max_length=5)),
            ],
        ),
    ]
