# Generated by Django 4.0 on 2023-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_sitesetting_title_seperator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='title_separator',
            field=models.CharField(default='-', max_length=5),
        ),
    ]
