# Generated by Django 4.0 on 2023-07-07 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_sitesetting_title_separator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='typing_speed',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
