# Generated by Django 4.0 on 2023-07-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_sitesetting_typing_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='typing_speed',
            field=models.IntegerField(default=100),
        ),
    ]
