# Generated by Django 4.0 on 2023-07-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_sitesetting_typing_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='border_glow',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='active_upper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='pfp_aura',
            field=models.CharField(default='#cf2866', max_length=10),
        ),
    ]
