# Generated by Django 4.0 on 2024-01-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_sitesetting_border_glow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='home_title',
            field=models.BooleanField(default=True),
        ),
    ]
