# Generated by Django 4.0 on 2024-02-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_sitesetting_home_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='title_separator',
            field=models.CharField(choices=[('-', '-'), ('–', '–'), ('—', '—'), ('_', '_'), ('.', '.'), ('::', '::'), ('|', '|')], default='-', max_length=5, verbose_name='Title Separator'),
        ),
    ]
