# Generated by Django 4.0 on 2024-02-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_sitesetting_title_separator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='blur_dropdown',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='theme',
            field=models.CharField(default='#cf2866', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='title_separator',
            field=models.CharField(choices=[('-', '-'), ('–', '–'), ('—', '—'), ('_', '_'), ('.', '.'), ('::', '::'), ('|', '|'), ('•', '•')], default='-', max_length=5, verbose_name='Title Separator'),
        ),
    ]
