# Generated by Django 4.1.4 on 2026-02-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_sitesetting_game_links_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='blog_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
