"""
Django settings for mrcheeezz project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from . import env
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.debug

# Minifys everying (js, css, html)
HTML_MINIFY = not DEBUG

FILE_UPLOAD_MAX_MEMORY_SIZE = 0

ALLOWED_HOSTS = env.allowed_hosts or [env.url]

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Packages
    'django_assets',
    'django_jinja',
    'whitenoise',
    'corsheaders',
    'taggit',
    'taggit_labels',
    'rest_framework',
    'colorfield',
    'admin_interface',

    # Apps
    'custom_admin',
    f'{env.base_name}',
    'api',
    'home',
    'about',
    'contact',
    'projects',
    'specs',
    'bots',
    'blog',
    'tags',
    'upload',
    'settings',
]

X_FRAME_OPTIONS='SAMEORIGIN'

CORS_ALLOWED_ORIGINS = env.cors_allowed_origins

MIDDLEWARE = [
    # Djanog
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom
    f'{env.base_name}.middlewares.StorePreviousURLMiddleware',
    f'{env.base_name}.middlewares.UnauthorizedMiddleware',

    # Packages
    'django_ratelimit.middleware.RatelimitMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

if HTML_MINIFY:
    MIDDLEWARE += [
        'htmlmin.middleware.HtmlMinifyMiddleware',
        'htmlmin.middleware.MarkRequestMiddleware',
    ]

ROOT_URLCONF = f'{env.base_name}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(PROJECT_ROOT / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Django
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Other
                f'{env.base_name}.context_processors.global_vars',
                'home.context_processors.g',
            ],
        },
    },
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [str(PROJECT_ROOT / 'templates' / 'jinja2')],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': f'{env.base_name}.jinja2.environment',
            'context_processors': [
                f'{env.base_name}.context_processors.global_vars',
            ],
        },
    },
]

WSGI_APPLICATION = f'{env.base_name}.wsgi.application'

# Logging
# https://docs.djangoproject.com/en/4.2/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(PROJECT_ROOT / 'logs' / 'django.log'),
            'formatter': 'simple',
        },
    },
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'uwsgi': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

if DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {'class': 'logging.StreamHandler'},
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }
else:
    os.makedirs(PROJECT_ROOT / 'logs', exist_ok=True)

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

if env.use_sqlite:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(PROJECT_ROOT / 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env.postgresql_name,
            'USER': env.postgresql_user,
            'PASSWORD': env.postgresql_password,
            'HOST': env.postgresql_host,
            'PORT': env.postgresql_port,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Ratelimit

RATELIMIT_VIEW = 'api.views.rate_limit'

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = str(PROJECT_ROOT / 'uploads')

STATIC_URL = '/static/'
STATIC_ROOT = str(PROJECT_ROOT / 'staticfiles')

STATICFILES_DIRS = [
    str(PROJECT_ROOT / 'static'),
]

# django-assets compiles from source static assets.
ASSETS_ROOT = str(PROJECT_ROOT / 'static')
ASSETS_URL = STATIC_URL
# Explicitly set webassets directory/load_path to avoid resolver recursion
# when using versioned output patterns (e.g. bundle.%(version)s.js).
ASSETS_DIRECTORY = ASSETS_ROOT
ASSETS_LOAD_PATH = [ASSETS_ROOT]

# Serve static files via finders in production too, so files generated in
# STATICFILES_DIRS (e.g. static/gen/* from django-assets) are served.
WHITENOISE_USE_FINDERS = True

# Assets
# https://django-assets.readthedocs.io
# In local debug mode, avoid external binary dependencies (e.g. uglifyjs).
if DEBUG:
    CSS_FILTERS = ['libsass', 'rcssmin']
    JS_FILTERS = ['rjsmin']
    ASSETS_DEBUG = False
    ASSETS_AUTO_BUILD = True
    ASSETS_CACHE = False
    ASSETS_MANIFEST = False
    ASSETS_VERSION = 'timestamp'
    ASSETS_VERSIONS = 'timestamp'
else:
    CSS_FILTERS = ['libsass', 'rcssmin']
    JS_FILTERS = ['rjsmin']
    ASSETS_DEBUG = False
    # Build missing bundles on demand in production-like runs so DEBUG=False
    # does not crash when /static/gen files are not pre-generated yet.
    ASSETS_AUTO_BUILD = True
    ASSETS_CACHE = False
    ASSETS_MANIFEST = False
    ASSETS_VERSION = 'timestamp'
    ASSETS_VERSIONS = 'timestamp'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Extra Variables
# No Link

STEAM_API_KEY = env.steam_api_key
STEAM_USER_ID = env.steam_user_id
NOW_PLAYING_KEY = env.NowPlayingID
