# Generated by Django 4.0 on 2023-06-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('github_repo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('website_name', models.CharField(blank=True, max_length=200, null=True)),
                ('streamer', models.CharField(max_length=200)),
                ('streamer_display', models.CharField(max_length=200)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_list', to='bots.bot')),
            ],
        ),
    ]
