# Generated by Django 4.0 on 2023-06-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botinstance',
            name='slug',
        ),
        migrations.AddField(
            model_name='bot',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
