# Generated by Django 4.0 on 2023-06-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_remove_botinstance_slug_bot_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='url',
        ),
    ]
