# Generated by Django 4.0 on 2023-06-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_remove_bot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinstance',
            name='out_of_commission',
            field=models.BooleanField(default=False),
        ),
    ]
