# Generated by Django 4.0 on 2023-06-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='specs')),
                ('pic_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='specs')),
                ('pic2_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('pic_count', models.IntegerField(default=0)),
                ('parts', models.ManyToManyField(to='specs.Part')),
            ],
        ),
    ]
