# Generated by Django 4.0 on 2023-06-12 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
