# Generated by Django 4.0 on 2024-02-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.BooleanField()),
                ('show_location', models.BooleanField()),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('show_age', models.BooleanField()),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_day', models.IntegerField()),
                ('programming_start', models.IntegerField()),
                ('artist', models.CharField(max_length=50)),
                ('song', models.CharField(max_length=50)),
                ('baseball', models.CharField(max_length=100)),
                ('nfl', models.CharField(max_length=100)),
                ('col_fbl', models.CharField(max_length=100)),
                ('hockey', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=255)),
                ('movie_platform', models.CharField(max_length=255)),
                ('tv_show', models.CharField(max_length=255)),
                ('tv_show_platform', models.CharField(max_length=255)),
                ('programming_languages', models.ManyToManyField(to='about.ProgrammingLanguage')),
            ],
        ),
    ]
