# Generated by Django 4.0 on 2024-02-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_programminglanguage_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='artist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='baseball',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='col_fbl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hockey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='movie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='movie_platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='nfl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='programming_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='show_age',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='show_location',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='song',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tv_show',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tv_show_platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='use',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
