# Generated by Django 4.0 on 2024-02-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_settings_artist_alter_settings_baseball_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='show_age',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='show_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='use',
            field=models.BooleanField(default=False),
        ),
    ]
