# Generated by Django 4.0 on 2023-09-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_spotifyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuser',
            name='user',
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='user_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='spotifyuser',
            unique_together={('user_id', 'spotify_user_id')},
        ),
    ]
