# Generated by Django 4.0 on 2023-09-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_spotifyuser_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyUser',
        ),
    ]
