# Generated by Django 4.1.4 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_apicredential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicredential",
            name="provider",
            field=models.CharField(
                choices=[
                    ("spotify", "Spotify"),
                    ("twitch", "Twitch"),
                    ("roblox", "Roblox"),
                    ("discord", "Discord"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
