# Generated by Django 4.0 on 2023-08-12 01:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog.models.upload_to_random_path', validators=['blog.models.validate_file_extension']),
        ),
    ]
