# Generated by Django 4.0 on 2023-06-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
