# Generated by Django 4.0 on 2023-06-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
