# Generated by Django 4.0 on 2023-07-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('link', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('svg', models.FileField(upload_to='icons/')),
                ('color', models.CharField(max_length=14)),
            ],
        ),
    ]
