# Generated by Django 4.0 on 2023-07-07 18:40

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='pfp',
            field=models.ImageField(upload_to=home.models.avatar_location),
        ),
    ]
