# Generated by Django 4.1.4 on 2026-02-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_home_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='social',
            name='platform',
            field=models.CharField(choices=[('discord', 'Discord'), ('spotify', 'Spotify'), ('twitch', 'Twitch'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('steam', 'Steam'), ('twitter', 'X/Twitter'), ('instagram', 'Instagram'), ('reddit', 'Reddit'), ('website', 'Website')], default='website', max_length=32),
        ),
        migrations.AddField(
            model_name='social',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='social',
            name='color',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='social',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
